package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func writeNativeMCPTestFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestProjectNativeMCPConvergesRegistriesAndAbsorbsLegacyBlock(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(t, inventoryPath, `{
  "imports": [],
  "mcpServers": {
    "reader": {"baseUrl": "https://mcp.example.test/mcp", "headers": {"X-Test": "${HOME}/token"}, "x-codex": {"defaultToolsApprovalMode": "approve"}},
    "local": {"command": "${HOME}/bin/server", "args": ["--stdio"], "env": {"CACHE": "${HOME}/cache"}, "x-codex": {"envVars": ["SESSION_TOKEN"], "toolTimeoutSec": 960}}
  }
}
`)
	writeNativeMCPTestFile(
		t,
		filepath.Join(home, ".claude.json"),
		`{"theme":"dark","mcpServers":{"stale":{"command":"old"}}}`+"\n",
	)
	writeNativeMCPTestFile(t, filepath.Join(home, ".codex", "config.toml"), `[features]
js_repl = false

`+legacyMCPBlockBegin+`
# Generated by agent-compose from the canonical mcporter inventory.
# Do not edit the managed block by hand.

[mcp_servers."reader"]
url = "https://old.example.test/mcp"

`+legacyMCPBlockEnd+`

[mcp_servers."local"]
command = "/old/server"

[mcp_servers."local".env]
STALE = "true"

[mcp_servers."computer-use"]
enabled = false
`)

	result, err := projectNativeMCP(nativeMCPOptions{
		Inventory:     inventoryPath,
		Home:          home,
		ProjectNative: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed || result.Servers != 2 {
		t.Fatalf("result = %+v, want two changed servers", result)
	}
	var claude map[string]any
	raw, err := os.ReadFile(filepath.Join(home, ".claude.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &claude); err != nil {
		t.Fatal(err)
	}
	if claude["theme"] != "dark" {
		t.Fatalf("Claude foreign state was not preserved: %v", claude)
	}
	servers := claude["mcpServers"].(map[string]any)
	if _, ok := servers["stale"]; ok {
		t.Fatalf("stale Claude server survived hard overwrite: %v", servers)
	}
	if got := servers["local"].(map[string]any)["command"]; got != filepath.Join(home, "bin", "server") {
		t.Fatalf("Claude home expansion = %v", got)
	}
	codexRaw, err := os.ReadFile(filepath.Join(home, ".codex", "config.toml"))
	if err != nil {
		t.Fatal(err)
	}
	codex := string(codexRaw)
	for _, want := range []string{
		`[mcp_servers."computer-use"]`,
		"enabled = false",
		aosMCPBlockBegin,
		`[mcp_servers."reader"]`,
		`[mcp_servers."local"]`,
		`default_tools_approval_mode = "approve"`,
		`env_vars = ["SESSION_TOKEN"]`,
		"tool_timeout_sec = 960",
		strconv.Quote(filepath.Join(home, "bin", "server")),
	} {
		if !strings.Contains(codex, want) {
			t.Fatalf("Codex projection missing %q:\n%s", want, codex)
		}
	}
	for _, stale := range []string{
		legacyMCPBlockBegin,
		"https://old.example.test/mcp",
		"/old/server",
		"STALE",
	} {
		if strings.Contains(codex, stale) {
			t.Fatalf("Codex projection retained stale config %q:\n%s", stale, codex)
		}
	}
	current, err := projectNativeMCP(nativeMCPOptions{
		Inventory:     inventoryPath,
		Home:          home,
		Check:         true,
		ProjectNative: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if current.Changed {
		t.Fatalf("second projection drifted: %+v", current)
	}
}

func TestProjectNativeMCPServerFallbackSkipsHarnessRegistries(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(
		t,
		inventoryPath,
		`{"imports":[],"mcpServers":{"reader":{"baseUrl":"https://mcp.example.test/mcp"}}}`+"\n",
	)
	result, err := projectNativeMCP(nativeMCPOptions{
		Inventory: inventoryPath,
		Home:      home,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed || result.Servers != 1 {
		t.Fatalf("unexpected fallback result: %+v", result)
	}
	if _, err := os.Stat(filepath.Join(home, ".mcporter", "mcporter.json")); err != nil {
		t.Fatalf("mcporter fallback was not written: %v", err)
	}
	if _, err := os.Stat(filepath.Join(home, ".claude.json")); !os.IsNotExist(err) {
		t.Fatalf("server fallback wrote Claude state: %v", err)
	}
	if _, err := os.Stat(filepath.Join(home, ".codex", "config.toml")); !os.IsNotExist(err) {
		t.Fatalf("server fallback wrote Codex state: %v", err)
	}
}

func TestProjectNativeMCPLegacyInventoryAddsEmptyImports(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(
		t,
		inventoryPath,
		`{"mcpServers":{"reader":{"baseUrl":"https://mcp.example.test/mcp"}}}`+"\n",
	)
	result, err := projectNativeMCP(nativeMCPOptions{
		Inventory: inventoryPath,
		Home:      home,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed || result.Servers != 1 {
		t.Fatalf("unexpected legacy projection result: %+v", result)
	}
	raw, err := os.ReadFile(filepath.Join(home, ".mcporter", "mcporter.json"))
	if err != nil {
		t.Fatal(err)
	}
	var projected struct {
		Imports []string                   `json:"imports"`
		Servers map[string]json.RawMessage `json:"mcpServers"`
	}
	if err := json.Unmarshal(raw, &projected); err != nil {
		t.Fatal(err)
	}
	if projected.Imports == nil || len(projected.Imports) != 0 {
		t.Fatalf("normalized imports = %#v, want explicit empty list", projected.Imports)
	}
	if _, ok := projected.Servers["reader"]; !ok {
		t.Fatalf("normalized inventory lost reader server: %s", raw)
	}
	current, err := projectNativeMCP(nativeMCPOptions{
		Inventory: inventoryPath,
		Home:      home,
	})
	if err != nil {
		t.Fatal(err)
	}
	if current.Changed {
		t.Fatalf("second legacy projection drifted: %+v", current)
	}
}

func TestProjectNativeMCPCheckDoesNotWrite(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(
		t,
		inventoryPath,
		`{"imports":[],"mcpServers":{"reader":{"baseUrl":"https://mcp.example.test/mcp"}}}`+"\n",
	)
	result, err := projectNativeMCP(nativeMCPOptions{
		Inventory:     inventoryPath,
		Home:          home,
		Check:         true,
		ProjectNative: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed {
		t.Fatal("check did not report missing projection")
	}
	if _, err := os.Stat(home); !os.IsNotExist(err) {
		t.Fatalf("check created the projected home: %v", err)
	}
}

func TestProjectNativeMCPRejectsUnsupportedApprovalMode(t *testing.T) {
	root := t.TempDir()
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(
		t,
		inventoryPath,
		`{"imports":[],"mcpServers":{"reader":{"baseUrl":"https://mcp.example.test/mcp","x-codex":{"defaultToolsApprovalMode":"never"}}}}`+"\n",
	)
	_, err := projectNativeMCP(nativeMCPOptions{
		Inventory:     inventoryPath,
		Home:          filepath.Join(root, "home"),
		ProjectNative: true,
	})
	if err == nil || !strings.Contains(
		err.Error(),
		`unsupported Codex approval mode "never"`,
	) {
		t.Fatalf("unsupported approval mode error = %v", err)
	}
}

func TestProjectNativeMCPRejectsNonEmptyImports(t *testing.T) {
	root := t.TempDir()
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(
		t,
		inventoryPath,
		`{"imports":["claude"],"mcpServers":{}}`+"\n",
	)
	_, err := projectNativeMCP(nativeMCPOptions{
		Inventory: inventoryPath,
		Home:      filepath.Join(root, "home"),
	})
	if err == nil || !strings.Contains(err.Error(), "inventory imports must be []") {
		t.Fatalf("non-empty imports error = %v", err)
	}
}

func TestProjectNativeMCPReadsEnvSourcedHeadersPerHarness(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	inventoryPath := filepath.Join(root, "mcporter.json")
	writeNativeMCPTestFile(t, inventoryPath, `{
  "imports": [],
  "mcpServers": {
    "jev": {"baseUrl": "http://mcp.example.test/mcp", "headers": {"x-agent-origin": "${ATERM_SESSION:-unseated}", "X-Static": "fixed"}, "x-codex": {"envHttpHeaders": {"x-agent-origin": "ATERM_SESSION"}}}
  }
}
`)
	if _, err := projectNativeMCP(nativeMCPOptions{Inventory: inventoryPath, Home: home, ProjectNative: true}); err != nil {
		t.Fatal(err)
	}
	var claude map[string]any
	raw, err := os.ReadFile(filepath.Join(home, ".claude.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &claude); err != nil {
		t.Fatal(err)
	}
	headers := claude["mcpServers"].(map[string]any)["jev"].(map[string]any)["headers"].(map[string]any)
	if headers["x-agent-origin"] != "${ATERM_SESSION:-unseated}" || headers["X-Static"] != "fixed" {
		t.Fatalf("Claude headers = %v, want the ${VAR} form Claude expands itself", headers)
	}
	codexRaw, err := os.ReadFile(filepath.Join(home, ".codex", "config.toml"))
	if err != nil {
		t.Fatal(err)
	}
	codex := string(codexRaw)
	if !strings.Contains(codex, `env_http_headers = { "x-agent-origin" = "ATERM_SESSION" }`) {
		t.Fatalf("Codex projection missing env_http_headers:\n%s", codex)
	}
	if !strings.Contains(codex, `"X-Static" = "fixed"`) {
		t.Fatalf("Codex projection lost the static header:\n%s", codex)
	}
	if strings.Contains(codex, "${ATERM_SESSION") {
		t.Fatalf("Codex would send the literal ${VAR} text:\n%s", codex)
	}
}

func TestLoadNativeMCPInventoryRefusesAMalformedEnvHeaderMapping(t *testing.T) {
	cases := map[string]string{
		"not a variable name": `"remote": {"baseUrl": "http://x.test/mcp", "x-codex": {"envHttpHeaders": {"x-agent-origin": "${ATERM_SESSION}"}}}`,
		"stdio server":        `"local": {"command": "server", "x-codex": {"envHttpHeaders": {"x-agent-origin": "ATERM_SESSION"}}}`,
	}
	for label, server := range cases {
		path := filepath.Join(t.TempDir(), "mcporter.json")
		writeNativeMCPTestFile(t, path, `{"imports": [], "mcpServers": {`+server+`}}`)
		if _, err := loadNativeMCPInventory(path); err == nil {
			t.Errorf("%s: inventory loaded, want a refusal", label)
		}
	}
}
