package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	aosMCPBlockBegin    = "# BEGIN AOS-managed MCP servers"
	aosMCPBlockEnd      = "# END AOS-managed MCP servers"
	legacyMCPBlockBegin = "# BEGIN agentic-os-kai mcporter-managed MCP servers"
	legacyMCPBlockEnd   = "# END agentic-os-kai mcporter-managed MCP servers"
)

var legacyMCPHeaderLines = []string{
	"# Generated by scripts/sync-codex-mcp.py from mcporter inventory.",
	"# Generated by agent-compose from the canonical mcporter inventory.",
	"# Do not edit the managed block by hand.",
}

type nativeMCPOptions struct {
	Inventory     string
	Home          string
	Check         bool
	ProjectNative bool
}

type nativeMCPResult struct {
	Servers int
	Changed bool
}

type nativeMCPServer struct {
	Command string            `json:"command"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
	Cwd     string            `json:"cwd"`
	URL     string            `json:"url"`
	BaseURL string            `json:"baseUrl"`
	Headers map[string]string `json:"headers"`
	Codex   nativeCodexPolicy `json:"x-codex"`
}

type nativeCodexPolicy struct {
	DefaultToolsApprovalMode string `json:"defaultToolsApprovalMode"`
	// EnvVars names variables Codex forwards from the harness to a stdio
	// server, which otherwise gets a filtered environment.
	EnvVars        []string `json:"envVars"`
	ToolTimeoutSec int      `json:"toolTimeoutSec"`
	// EnvHTTPHeaders maps a header to the variable Codex reads it from, since
	// Codex sends `headers` literally where Claude expands `${VAR}` in them.
	EnvHTTPHeaders map[string]string `json:"envHttpHeaders"`
}

type nativeMCPInventory struct {
	Raw     []byte
	Servers map[string]nativeMCPServer
}

func projectNativeMCP(opts nativeMCPOptions) (nativeMCPResult, error) {
	inventory, err := loadNativeMCPInventory(opts.Inventory)
	if err != nil {
		return nativeMCPResult{}, err
	}
	home := strings.TrimSpace(opts.Home)
	if home == "" {
		home, err = os.UserHomeDir()
		if err != nil {
			return nativeMCPResult{}, fmt.Errorf("native MCP: resolve home: %w", err)
		}
	}
	mcporterPath := filepath.Join(home, ".mcporter", "mcporter.json")
	mcporterChanged := !fileHasBytes(mcporterPath, inventory.Raw)
	result := nativeMCPResult{
		Servers: len(inventory.Servers),
		Changed: mcporterChanged,
	}

	var claudePath, codexPath string
	var claudePayload, codexPayload []byte
	var claudeChanged, codexChanged bool
	if opts.ProjectNative {
		claudePath = nativeClaudeConfigPath(home)
		codexPath = filepath.Join(home, ".codex", "config.toml")
		claudePayload, claudeChanged, err = renderNativeClaude(
			claudePath,
			inventory.Servers,
			home,
		)
		if err != nil {
			return nativeMCPResult{}, err
		}
		codexPayload, codexChanged, err = renderNativeCodex(
			codexPath,
			inventory.Servers,
			home,
		)
		if err != nil {
			return nativeMCPResult{}, err
		}
		result.Changed = result.Changed || claudeChanged || codexChanged
	}
	if opts.Check || !result.Changed {
		return result, nil
	}
	if mcporterChanged {
		if err := writeAtomicFile(mcporterPath, inventory.Raw, 0o600); err != nil {
			return nativeMCPResult{}, fmt.Errorf(
				"native MCP: write mcporter home inventory: %w",
				err,
			)
		}
	}
	if claudeChanged {
		if err := writeAtomicFile(nativeClaudeWritePath(claudePath), claudePayload, 0o600); err != nil {
			return nativeMCPResult{}, fmt.Errorf("native MCP: write Claude registry: %w", err)
		}
	}
	if codexChanged {
		if err := writeAtomicFile(codexPath, codexPayload, 0o600); err != nil {
			return nativeMCPResult{}, fmt.Errorf("native MCP: write Codex registry: %w", err)
		}
	}
	return result, nil
}

func loadNativeMCPInventory(path string) (nativeMCPInventory, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: inventory path is required")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: read inventory: %w", err)
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: parse inventory: %w", err)
	}
	if top == nil {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: inventory must be a JSON object")
	}
	importsRaw, ok := top["imports"]
	if !ok {
		importsRaw = json.RawMessage("[]")
		top["imports"] = importsRaw
		raw, err = json.MarshalIndent(top, "", "  ")
		if err != nil {
			return nativeMCPInventory{}, fmt.Errorf(
				"native MCP: normalize legacy inventory: %w",
				err,
			)
		}
	}
	var imports []string
	if err := json.Unmarshal(importsRaw, &imports); err != nil || len(imports) != 0 {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: inventory imports must be []")
	}
	var servers map[string]nativeMCPServer
	if err := json.Unmarshal(top["mcpServers"], &servers); err != nil {
		return nativeMCPInventory{}, fmt.Errorf("native MCP: parse mcpServers: %w", err)
	}
	if servers == nil {
		servers = map[string]nativeMCPServer{}
	}
	for name, config := range servers {
		if strings.TrimSpace(name) == "" {
			return nativeMCPInventory{}, fmt.Errorf("native MCP: server name must not be empty")
		}
		if config.endpoint() == "" && strings.TrimSpace(config.Command) == "" {
			return nativeMCPInventory{}, fmt.Errorf(
				"native MCP: server %q has neither URL nor command",
				name,
			)
		}
		mode := strings.TrimSpace(config.Codex.DefaultToolsApprovalMode)
		if !validNativeCodexApprovalMode(mode) {
			return nativeMCPInventory{}, fmt.Errorf(
				"native MCP: server %q has unsupported Codex approval mode %q",
				name,
				mode,
			)
		}
		config.Codex.DefaultToolsApprovalMode = mode
		if err := validateNativeEnvHTTPHeaders(name, config); err != nil {
			return nativeMCPInventory{}, err
		}
		servers[name] = config
	}
	return nativeMCPInventory{
		Raw:     appendNativeTrailingNewline(raw),
		Servers: servers,
	}, nil
}

func validNativeCodexApprovalMode(mode string) bool {
	switch mode {
	case "", "auto", "prompt", "writes", "approve":
		return true
	default:
		return false
	}
}

var nativeEnvVarName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func validateNativeEnvHTTPHeaders(name string, config nativeMCPServer) error {
	if len(config.Codex.EnvHTTPHeaders) == 0 {
		return nil
	}
	if config.endpoint() == "" {
		return fmt.Errorf("native MCP: server %q sets x-codex.envHttpHeaders without a URL", name)
	}
	for header, variable := range config.Codex.EnvHTTPHeaders {
		if strings.TrimSpace(header) == "" || !nativeEnvVarName.MatchString(variable) {
			return fmt.Errorf(
				"native MCP: server %q maps header %q to %q, which is not an environment variable name",
				name,
				header,
				variable,
			)
		}
	}
	return nil
}

// nativeCodexStaticHeaders drops every header Codex reads from the environment,
// so the literal `${VAR}` form meant for Claude never reaches the wire.
func nativeCodexStaticHeaders(config nativeMCPServer) map[string]string {
	static := make(map[string]string, len(config.Headers))
	for header, value := range config.Headers {
		fromEnv := false
		for envHeader := range config.Codex.EnvHTTPHeaders {
			if strings.EqualFold(header, envHeader) {
				fromEnv = true
				break
			}
		}
		if !fromEnv {
			static[header] = value
		}
	}
	return static
}

func (server nativeMCPServer) endpoint() string {
	if strings.TrimSpace(server.URL) != "" {
		return server.URL
	}
	return server.BaseURL
}

func renderNativeClaude(
	path string,
	servers map[string]nativeMCPServer,
	home string,
) ([]byte, bool, error) {
	top := map[string]json.RawMessage{}
	if raw, err := os.ReadFile(path); err == nil {
		if err := json.Unmarshal(raw, &top); err != nil {
			return nil, false, fmt.Errorf("native MCP: parse Claude config: %w", err)
		}
	} else if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("native MCP: read Claude config: %w", err)
	}
	desired := map[string]any{}
	for name, config := range servers {
		desired[name] = nativeClaudeServer(config, home)
	}
	mcpRaw, err := json.Marshal(desired)
	if err != nil {
		return nil, false, fmt.Errorf("native MCP: render Claude servers: %w", err)
	}
	var desiredComparable map[string]any
	if err := json.Unmarshal(mcpRaw, &desiredComparable); err != nil {
		return nil, false, fmt.Errorf("native MCP: normalize Claude servers: %w", err)
	}
	var current map[string]any
	if raw := top["mcpServers"]; len(raw) > 0 {
		_ = json.Unmarshal(raw, &current)
	}
	if reflect.DeepEqual(current, desiredComparable) {
		return nil, false, nil
	}
	top["mcpServers"] = mcpRaw
	payload, err := json.MarshalIndent(top, "", "  ")
	if err != nil {
		return nil, false, fmt.Errorf("native MCP: render Claude config: %w", err)
	}
	return appendNativeTrailingNewline(payload), true, nil
}

func nativeClaudeServer(config nativeMCPServer, home string) map[string]any {
	if endpoint := config.endpoint(); strings.TrimSpace(endpoint) != "" {
		output := map[string]any{
			"type": "http",
			"url":  expandNativeHome(endpoint, home),
		}
		if len(config.Headers) > 0 {
			output["headers"] = expandNativeMap(config.Headers, home)
		}
		return output
	}
	output := map[string]any{
		"command": expandNativeHomePath(config.Command, home),
	}
	if len(config.Args) > 0 {
		output["args"] = expandNativeSlice(config.Args, home)
	}
	if len(config.Env) > 0 {
		output["env"] = expandNativeMap(config.Env, home)
	}
	if strings.TrimSpace(config.Cwd) != "" {
		output["cwd"] = expandNativeHomePath(config.Cwd, home)
	}
	return output
}

func renderNativeCodex(
	path string,
	servers map[string]nativeMCPServer,
	home string,
) ([]byte, bool, error) {
	existing := ""
	if raw, err := os.ReadFile(path); err == nil {
		existing = string(raw)
	} else if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("native MCP: read Codex config: %w", err)
	}
	base := removeNativeManagedBlock(existing, legacyMCPBlockBegin, legacyMCPBlockEnd)
	base = removeNativeManagedBlock(base, aosMCPBlockBegin, aosMCPBlockEnd)
	base = stripNativeCodexServerTables(base, servers)
	base = stripNativeLegacyHeaders(base)
	rendered := appendNativeManagedBlock(base, nativeCodexBlock(servers, home))
	return []byte(rendered), rendered != existing, nil
}

func nativeCodexBlock(servers map[string]nativeMCPServer, home string) string {
	var output strings.Builder
	output.WriteString(aosMCPBlockBegin + "\n")
	output.WriteString("# Generated by AOS from the canonical mcporter inventory.\n")
	output.WriteString("# Do not edit this managed block by hand.\n\n")
	for _, name := range sortedNativeKeys(servers) {
		config := servers[name]
		fmt.Fprintf(&output, "[mcp_servers.%s]\n", strconv.Quote(name))
		if endpoint := config.endpoint(); strings.TrimSpace(endpoint) != "" {
			fmt.Fprintf(
				&output,
				"url = %s\n",
				strconv.Quote(expandNativeHome(endpoint, home)),
			)
			if static := nativeCodexStaticHeaders(config); len(static) > 0 {
				fmt.Fprintf(
					&output,
					"http_headers = %s\n",
					nativeTOMLMap(expandNativeMap(static, home)),
				)
			}
			if len(config.Codex.EnvHTTPHeaders) > 0 {
				fmt.Fprintf(
					&output,
					"env_http_headers = %s\n",
					nativeTOMLMap(config.Codex.EnvHTTPHeaders),
				)
			}
		} else {
			fmt.Fprintf(
				&output,
				"command = %s\n",
				strconv.Quote(expandNativeHomePath(config.Command, home)),
			)
			if len(config.Args) > 0 {
				fmt.Fprintf(
					&output,
					"args = %s\n",
					nativeTOMLSlice(expandNativeSlice(config.Args, home)),
				)
			}
			if len(config.Env) > 0 {
				fmt.Fprintf(
					&output,
					"env = %s\n",
					nativeTOMLMap(expandNativeMap(config.Env, home)),
				)
			}
			if strings.TrimSpace(config.Cwd) != "" {
				fmt.Fprintf(
					&output,
					"cwd = %s\n",
					strconv.Quote(expandNativeHomePath(config.Cwd, home)),
				)
			}
		}
		if config.Codex.DefaultToolsApprovalMode != "" {
			fmt.Fprintf(
				&output,
				"default_tools_approval_mode = %s\n",
				strconv.Quote(config.Codex.DefaultToolsApprovalMode),
			)
		}
		if len(config.Codex.EnvVars) > 0 {
			fmt.Fprintf(&output, "env_vars = %s\n", nativeTOMLSlice(config.Codex.EnvVars))
		}
		if config.Codex.ToolTimeoutSec > 0 {
			fmt.Fprintf(&output, "tool_timeout_sec = %d\n", config.Codex.ToolTimeoutSec)
		}
		output.WriteString("\n")
	}
	output.WriteString(aosMCPBlockEnd + "\n")
	return output.String()
}

func removeNativeManagedBlock(existing, begin, end string) string {
	for {
		start := strings.Index(existing, begin)
		if start < 0 {
			return existing
		}
		finish := strings.Index(existing[start:], end)
		if finish < 0 {
			return existing
		}
		finish = start + finish + len(end)
		existing = existing[:start] + existing[finish:]
	}
}

func appendNativeManagedBlock(existing, block string) string {
	if strings.TrimSpace(existing) == "" {
		return block
	}
	return strings.TrimSpace(existing) + "\n\n" + block
}

func stripNativeCodexServerTables(
	existing string,
	servers map[string]nativeMCPServer,
) string {
	lines := strings.SplitAfter(existing, "\n")
	kept := make([]string, 0, len(lines))
	drop := false
	for _, line := range lines {
		if tablePath, ok := nativeTOMLTablePath(line); ok {
			drop = len(tablePath) >= 2 && tablePath[0] == "mcp_servers"
			if drop {
				_, drop = servers[tablePath[1]]
			}
		}
		if !drop {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "")
}

func nativeTOMLTablePath(line string) ([]string, bool) {
	header := strings.TrimSpace(stripNativeTOMLComment(line))
	array := strings.HasPrefix(header, "[[") && strings.HasSuffix(header, "]]")
	if array {
		header = strings.TrimSpace(header[2 : len(header)-2])
	} else if strings.HasPrefix(header, "[") && strings.HasSuffix(header, "]") {
		header = strings.TrimSpace(header[1 : len(header)-1])
	} else {
		return nil, false
	}
	var tablePath []string
	for index := 0; index < len(header); {
		for index < len(header) && (header[index] == ' ' || header[index] == '\t') {
			index++
		}
		if index == len(header) {
			return nil, false
		}
		var key string
		switch header[index] {
		case '"':
			start := index
			index++
			escaped := false
			for index < len(header) {
				if header[index] == '"' && !escaped {
					index++
					break
				}
				if header[index] == '\\' && !escaped {
					escaped = true
				} else {
					escaped = false
				}
				index++
			}
			if index > len(header) || header[index-1] != '"' {
				return nil, false
			}
			decoded, err := strconv.Unquote(header[start:index])
			if err != nil {
				return nil, false
			}
			key = decoded
		case '\'':
			index++
			start := index
			for index < len(header) && header[index] != '\'' {
				index++
			}
			if index == len(header) {
				return nil, false
			}
			key = header[start:index]
			index++
		default:
			start := index
			for index < len(header) &&
				header[index] != '.' &&
				header[index] != ' ' &&
				header[index] != '\t' {
				index++
			}
			key = header[start:index]
		}
		if key == "" {
			return nil, false
		}
		tablePath = append(tablePath, key)
		for index < len(header) && (header[index] == ' ' || header[index] == '\t') {
			index++
		}
		if index == len(header) {
			return tablePath, true
		}
		if header[index] != '.' {
			return nil, false
		}
		index++
	}
	return nil, false
}

func stripNativeTOMLComment(line string) string {
	var quote byte
	escaped := false
	for index := 0; index < len(line); index++ {
		switch {
		case quote == '"' && line[index] == '\\' && !escaped:
			escaped = true
		case quote != 0 && line[index] == quote && !escaped:
			quote = 0
		case quote == 0 && (line[index] == '"' || line[index] == '\''):
			quote = line[index]
		case quote == 0 && line[index] == '#':
			return line[:index]
		default:
			escaped = false
		}
	}
	return line
}

func stripNativeLegacyHeaders(text string) string {
	lines := strings.Split(text, "\n")
	kept := lines[:0]
	for _, line := range lines {
		skip := false
		for _, legacy := range legacyMCPHeaderLines {
			if line == legacy {
				skip = true
				break
			}
		}
		if !skip {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func nativeTOMLSlice(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func nativeTOMLMap(values map[string]string) string {
	keys := sortedNativeKeys(values)
	items := make([]string, 0, len(keys))
	for _, key := range keys {
		items = append(
			items,
			strconv.Quote(key)+" = "+strconv.Quote(values[key]),
		)
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func expandNativeHome(value, home string) string {
	return strings.ReplaceAll(value, "${HOME}", home)
}

func expandNativeHomePath(value, home string) string {
	expanded := expandNativeHome(value, home)
	if strings.Contains(value, "${HOME}") {
		return filepath.Clean(filepath.FromSlash(expanded))
	}
	return expanded
}

func expandNativeSlice(values []string, home string) []string {
	output := make([]string, len(values))
	for index, value := range values {
		output[index] = expandNativeHome(value, home)
	}
	return output
}

func expandNativeMap(values map[string]string, home string) map[string]string {
	output := make(map[string]string, len(values))
	for key, value := range values {
		output[key] = expandNativeHome(value, home)
	}
	return output
}

func sortedNativeKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func appendNativeTrailingNewline(raw []byte) []byte {
	return append([]byte(strings.TrimRight(string(raw), "\r\n")), '\n')
}
